// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ncmnI4wrFYHxIYrNfBUecYF_OxlmKsc',
    appId: '1:832511007876:web:547d4f7f9a51c3bf8bb6d1',
    messagingSenderId: '832511007876',
    projectId: 'final-exam-79514',
    authDomain: 'final-exam-79514.firebaseapp.com',
    storageBucket: 'final-exam-79514.firebasestorage.app',
    measurementId: 'G-79JM0FG3J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGsZYBAIN--h_p2W4IvMmwc091mobjzo',
    appId: '1:832511007876:android:b62b351e786923e48bb6d1',
    messagingSenderId: '832511007876',
    projectId: 'final-exam-79514',
    storageBucket: 'final-exam-79514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpif6cxmq_GGHAMeABvftZefDOfTyM-s',
    appId: '1:832511007876:ios:fbc9628936f23c038bb6d1',
    messagingSenderId: '832511007876',
    projectId: 'final-exam-79514',
    storageBucket: 'final-exam-79514.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpif6cxmq_GGHAMeABvftZefDOfTyM-s',
    appId: '1:832511007876:ios:fbc9628936f23c038bb6d1',
    messagingSenderId: '832511007876',
    projectId: 'final-exam-79514',
    storageBucket: 'final-exam-79514.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ncmnI4wrFYHxIYrNfBUecYF_OxlmKsc',
    appId: '1:832511007876:web:bd32d654504b58768bb6d1',
    messagingSenderId: '832511007876',
    projectId: 'final-exam-79514',
    authDomain: 'final-exam-79514.firebaseapp.com',
    storageBucket: 'final-exam-79514.firebasestorage.app',
    measurementId: 'G-J4CSWFSKBG',
  );
}
